# Generated by Django 4.0.4 on 2022-04-26 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libary_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin_Details',
        ),
        migrations.DeleteModel(
            name='Book_Details',
        ),
    ]
