# Generated by Django 4.0.4 on 2022-04-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libary_app', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_details',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
