# Generated by Django 4.0.4 on 2022-04-26 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libary_app', '0004_alter_admin_details_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book_Details',
        ),
    ]
