# Generated by Django 4.0.4 on 2022-04-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libary_app', '0005_delete_book_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_name', models.CharField(max_length=15)),
                ('Authors', models.CharField(max_length=20)),
                ('Book_code', models.IntegerField()),
            ],
        ),
    ]
