# Generated by Django 4.0.4 on 2022-04-26 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libary_app', '0007_alter_book_details_authors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_details',
            name='Authors',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book_details',
            name='Book_name',
            field=models.CharField(max_length=100),
        ),
    ]
